version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongodb_data:/data/db

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load_balancer
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - server_app
    links:
      - mongodb
    networks:
      - my_network

  server_app:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_app
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:
