# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR .

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the load balancer files to the working directory
COPY . .
# Expose the port on which your load balancer listens (assumed to be 3000)
EXPOSE 3000

# Start the load balancer
CMD ["node", "loadBalance.js"]
