version: "3.8"
services:

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load_balancer
    restart: always
    environment:
      SERVER: server_app
    ports:
      - "3000:3000"
    depends_on:
      - server_app
    networks:
      - my_network

  server_app:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_app
    restart: always
    ports:
      - "3001:3001"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

